# Auto-generated anime database.
#
# The full catalog lives in anime_data.json (generated by
# scripts/fetch_anime_catalog.py --build and enriched by
# scripts/enrich_details.py). The catalog is ~58MB of JSON, which is
# ~365MB as Python objects -- too much to load eagerly on low-memory
# hosts like Render's 512MB free tier. It is now loaded on first access
# (pages that never touch the catalog, like /characters, never pay for
# it), and reloads are skipped when memory is tight.
import json
import os
import threading

_DIR = os.path.dirname(os.path.abspath(__file__))

_DATA_PATH = os.path.join(_DIR, "anime_data.json")

_reload_lock = threading.Lock()

# TVmaze serves two flavors of the same episode still: the compressed
# proxy (/uploads/images/original/ and /uploads/images/medium*/) and the
# full-res master (/uploads/images/original_untouched/, 1920x1080 when
# available). Rewriting the URL flavor is a pure string swap -- no API
# calls -- so every consumer of the catalog serves HD thumbs.
_TVMAZE_HD_FLAVORS = (
    "/uploads/images/medium_landscape/",
    "/uploads/images/medium/",
    "/uploads/images/original/",
)
_TVMAZE_HD_FLAVOR = "/uploads/images/original_untouched/"
# AniList covers likewise come in ~230px medium and ~460px+ large; review
# cards render them at retina sizes, so prefer the large flavor.
_ANILIST_MEDIUM = "/media/anime/cover/medium/"
_ANILIST_LARGE = "/media/anime/cover/large/"


def _upgrade_image_flavors(catalog):
    """Rewrite low-res image URL flavors to their HD equivalents, in
    place. Cheap (string ops only) and applied once per catalog load."""
    for entry in catalog.values():
        image = entry.get("image")
        if isinstance(image, str) and _ANILIST_MEDIUM in image:
            entry["image"] = image.replace(_ANILIST_MEDIUM, _ANILIST_LARGE)
        for season in entry.get("seasons") or ():
            for ep in season.get("episodes") or ():
                thumb = ep.get("thumb")
                if isinstance(thumb, str) and "static.tvmaze.com/uploads/images/" in thumb:
                    for old in _TVMAZE_HD_FLAVORS:
                        if old in thumb:
                            ep["thumb"] = thumb.replace(old, _TVMAZE_HD_FLAVOR)
                            break


class _LazyCatalog(dict):
    """A dict that loads anime_data.json the first time anything reads
    it. `from anime_data import anime_database` still binds the same
    object (we mutate in place), so all existing call sites keep working.
    """

    _loaded = False

    def _ensure(self):
        if not self._loaded:
            with _reload_lock:
                if not self._loaded:
                    with open(_DATA_PATH, "r", encoding="utf-8") as _f:
                        self.update(json.load(_f))
                    _upgrade_image_flavors(self)
                    self._loaded = True

    def __getitem__(self, key):
        self._ensure()
        return dict.__getitem__(self, key)

    def __contains__(self, key):
        self._ensure()
        return dict.__contains__(self, key)

    def __iter__(self):
        self._ensure()
        return dict.__iter__(self)

    def __len__(self):
        self._ensure()
        return dict.__len__(self)

    def get(self, key, default=None):
        self._ensure()
        return dict.get(self, key, default)

    def items(self):
        self._ensure()
        return dict.items(self)

    def values(self):
        self._ensure()
        return dict.values(self)

    def keys(self):
        self._ensure()
        return dict.keys(self)

    def copy(self):
        self._ensure()
        return dict.copy(self)


anime_database = _LazyCatalog()


def preload_catalog():
    """Start loading the catalog in a background thread so the first
    request doesn't block for the full 58 MB parse."""
    if not anime_database._loaded:
        t = threading.Thread(target=anime_database._ensure, daemon=True)
        t.start()


def _rss_mb():
    try:
        import resource
        return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024
    except Exception:
        return 9999


def reload_database():
    """Reload anime_data.json into the catalog.

    Called by the auto-enrichment background thread so the running app
    picks up new episode thumbnails, airing changes, and TBC updates
    without requiring a restart. Reloading while the old catalog is
    resident temporarily holds both old + new in memory, which can
    OOM-kill low-memory hosts -- so on Render (RENDER=true) it's skipped
    when the process is already using a lot of RAM. (On Render the
    enrichment loops are disabled entirely; data ships with the repo.)
    """
    on_render = bool(os.environ.get("RENDER"))
    if on_render and _rss_mb() > 300:
        print("[anime_data] skipping catalog reload: memory tight", flush=True)
        return
    with _reload_lock:
        with open(_DATA_PATH, "r", encoding="utf-8") as _f:
            new = json.load(_f)
        anime_database.clear()
        anime_database.update(new)
        _upgrade_image_flavors(anime_database)
        anime_database._loaded = True
