# Auto-generated anime database.
#
# The full catalog lives in anime_data.json (generated by
# scripts/fetch_anime_catalog.py --build and enriched by
# scripts/enrich_details.py). It is loaded here at import time -- keeping the
# catalog in a plain JSON file instead of a Python literal avoids compiling a
# multi-hundred-MB code object, which was OOM-killing the app in low-memory
# containers.
import json
import os
import threading

_DIR = os.path.dirname(os.path.abspath(__file__))

_DATA_PATH = os.path.join(_DIR, "anime_data.json")

with open(_DATA_PATH, "r", encoding="utf-8") as _f:
    anime_database = json.load(_f)

_reload_lock = threading.Lock()


def reload_database():
    """Reload anime_data.json into the global anime_database dict.

    Called by the auto-enrichment background thread so the running app
    picks up new episode thumbnails, airing changes, and TBC updates
    without requiring a restart.
    """
    global anime_database
    with _reload_lock:
        with open(_DATA_PATH, "r", encoding="utf-8") as _f:
            anime_database = json.load(_f)
