import functools
import os

from dotenv import load_dotenv
load_dotenv()

from flask import Flask, render_template, request, jsonify, g, url_for
from anime_data import anime_database
from database import create_tables, get_connection, get_anime_stats, get_all_anime_stats, add_review

from auth import auth, load_logged_in_user
from chat import chat_bp

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "dev-insecure-change-me")

app.register_blueprint(auth)
app.register_blueprint(chat_bp)


@app.before_request
def _attach_user():
    load_logged_in_user()


@app.context_processor
def _inject_user():
    return {"current_user": g.get("user")}


@app.template_filter("anime_img")
def anime_img(image):
    """Templates call {{ image | anime_img }}. Local filenames resolve to
    /static/images/anime/<name>; full URLs (AniList CDN) pass through."""
    if image.startswith(("http://", "https://")):
        return image
    return url_for("static", filename="images/anime/" + image)


# The full catalog lives in anime_data.py (5000+ titles, auto-generated by
# scripts/fetch_anime_catalog.py). Helpers below build sorted/filtered views.

SORT_TITLES = {
    "latest": "Latest Releases",
    "popular": "Most Popular",
    "trending": "Trending Now",
    "critics": "Critics' Picks",
    "underrated": "Hidden Gems (Underrated)",
}


@functools.lru_cache(maxsize=1)
def _cached_genres():
    """Derive the genre list from the catalog, most common first."""
    from collections import Counter

    counter = Counter()
    for entry in anime_database.values():
        for genre in entry.get("genre", "").split(" \u2022 "):
            genre = genre.strip()
            if genre and genre.lower() != "anime":
                counter[genre] += 1
    return [g for g, _ in counter.most_common(20)]


def _genre_list():
    return _cached_genres()


def _sort_value(entry, sort):
    rating = entry.get("rating")
    try:
        rating = float(rating)
    except (TypeError, ValueError):
        rating = 0.0
    popularity = entry.get("member_count", 0) or 0
    year = entry.get("release", "")
    try:
        year = int(year)
    except (TypeError, ValueError):
        year = 0

    if sort == "popular":
        return (popularity, rating)
    if sort == "critics":
        return (rating, popularity)
    if sort == "underrated":
        # High rating but low popularity = hidden gems.
        return (rating, -popularity)
    if sort == "trending":
        return (year, popularity)
    return (year, popularity)  # latest


def _catalog_entries(sort="latest", genre=None, limit=None):
    """Return catalog entries enriched with live rating/votes, sorted and
    optionally filtered by genre. Used by home + browse + category pages."""
    all_stats = get_all_anime_stats()

    entries = []
    for slug, entry in anime_database.items():
        if genre:
            genres = entry.get("genre", "").lower()
            if genre.lower() not in genres:
                continue

        stats = all_stats.get(slug, {"votes": 0, "average": 0})
        live_rating = stats["average"] if stats["votes"] > 0 else entry.get("rating", "N/A")
        entries.append({
            "slug": slug,
            "title": entry.get("title", slug),
            "image": entry.get("image", ""),
            "live_rating": live_rating,
            "live_votes": stats["votes"],
            "member_count": entry.get("member_count", 0) or 0,
            "rating": entry.get("rating", "N/A"),
            "release": entry.get("release", ""),
            "genre": entry.get("genre", ""),
            "status": entry.get("status", ""),
        })

    entries.sort(key=lambda e: _sort_value(e, sort), reverse=True)

    if limit:
        entries = entries[:limit]

    return entries


@app.route("/")
def home():
    """Homepage shows the LATEST releases (most recent first) -- the full
    catalog lives behind the Browse links in the navbar."""
    latest = _catalog_entries(sort="latest", limit=48)

    return render_template(
        "index.html",
        anime_list=latest,
        page_title="Latest Releases",
        genres=_genre_list(),
    )


@app.route("/browse")
def browse():
    sort = request.args.get("sort", "popular")
    if sort not in SORT_TITLES:
        sort = "popular"

    entries = _catalog_entries(sort=sort)

    return render_template(
        "browse.html",
        anime_list=entries,
        page_title=SORT_TITLES[sort],
        active_sort=sort,
        sort_titles=SORT_TITLES,
        genres=_genre_list(),
    )


@app.route("/category/<genre>")
def category(genre):
    entries = _catalog_entries(sort="popular", genre=genre)

    return render_template(
        "browse.html",
        anime_list=entries,
        page_title=f"{genre} Anime",
        active_genre=genre,
        sort_titles=SORT_TITLES,
        genres=_genre_list(),
    )


@app.route("/api/search")
def api_search():
    """Search the FULL catalog (not just the home page grid). Returns JSON so
    the navbar search can open an anime page directly."""
    q = (request.args.get("q") or "").strip().lower()
    if not q:
        return jsonify({"success": True, "results": []})

    results = []
    for slug, entry in anime_database.items():
        title = entry.get("title", "")
        if q in title.lower():
            results.append({
                "slug": slug,
                "title": title,
                "image": entry.get("image", ""),
                "year": entry.get("release", ""),
                "rating": entry.get("rating", "N/A"),
            })
        if len(results) >= 12:
            break

    return jsonify({"success": True, "results": results})


@app.route("/anime/<anime_slug>")
def anime(anime_slug):
    anime = anime_database.get(anime_slug)

    if anime is None:
        return "Anime not found", 404

    return render_template(
        "anime.html",
        anime=anime
    )


@app.route("/community/<anime_slug>")
def community(anime_slug):
    entry = anime_database.get(anime_slug)

    if entry is None:
        return "Anime not found", 404

    return render_template(
        "community.html",
        anime_name=entry.get("title", anime_slug),
        anime_image=entry.get("image", ""),
        anime_slug=anime_slug
    )


@app.route("/anime-reviews/<anime_slug>", methods=["GET"])
def anime_reviews(anime_slug):
    """Returns the live average rating, vote breakdown, and every review
    written for this anime, computed straight from the database."""

    if anime_slug not in anime_database:
        return jsonify({"success": False, "error": "Anime not found"}), 404

    stats = get_anime_stats(anime_slug)

    return jsonify({
        "success": True,
        "average": stats["average"],
        "votes": stats["votes"],
        "breakdown": stats["breakdown"],
        "reviews": stats["reviews"],
    })


@app.route("/rate-anime", methods=["POST"])
def rate_anime():
    """Accepts a star rating (1-5) plus an optional username and review
    text, stores it, and returns the freshly recalculated average across
    every rating submitted so far."""

    data = request.get_json(silent=True) or {}

    anime_slug = data.get("anime_slug")
    rating = data.get("rating")
    username = (data.get("username") or "Anonymous").strip()[:40] or "Anonymous"
    comment = (data.get("comment") or "").strip()[:1000]

    if not anime_slug or anime_slug not in anime_database:
        return jsonify({"success": False, "error": "Unknown anime"}), 404

    try:
        rating = int(rating)
    except (TypeError, ValueError):
        return jsonify({"success": False, "error": "Rating must be a number"}), 400

    if rating < 1 or rating > 5:
        return jsonify({"success": False, "error": "Rating must be between 1 and 5"}), 400

    add_review(anime_slug, username, rating, comment)

    stats = get_anime_stats(anime_slug)

    return jsonify({
        "success": True,
        "average": stats["average"],
        "votes": stats["votes"],
        "breakdown": stats["breakdown"],
        "reviews": stats["reviews"],
    })


@app.route("/find-mood")
def find_mood():
    return render_template("find_mood.html")

if __name__ == "__main__":
    create_tables()
    # Bind to 0.0.0.0 and honor the PORT env var so the managed preview can
    # reach the dev server. The reloader subprocess is disabled because the
    # platform manages the process lifecycle.
    app.run(
        host="0.0.0.0",
        port=int(os.environ.get("PORT", "5000")),
        debug=True,
        use_reloader=False,
    )
